---

AWSTemplateFormatVersion: '2010-09-09'
Description: CD pipeline

Parameters:
  Service:
    Description: Name of the service, propagated all over the place. Choose wisely.
    Type: String
    AllowedPattern: '^[a-z]+(-[a-z]+)*$'
    ConstraintDescription: must contain only lowercase letters and hyphens

  GitHubRepo:
    Type: String
    Default: cfn-macro-uselatest
    AllowedPattern: '[A-Za-z0-9-]+'

  GitHubRepoOwner:
    Type: String
    Default: milancermak
    AllowedPattern: '[A-Za-z0-9-]+'

  GitHubRepoBranch:
    Type: String
    Default: master
    AllowedPattern: '[A-Za-z0-9-]+'

  # note: the GitHub OAuth token is made available via Secrets Manager:
  # '{{resolve:secretsmanager:/shared/github-oauth-token}}'


  RegionalArtifactsBucketPrefix:
    Description: Prefix of the artifact buckets used across regions
    Type: String
    Default: 'cfn-macro-uselatest-pipeline-artifacts'

Resources:
  CloudformationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - cloudformation.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - codebuild.amazonaws.com
      Policies:
        - PolicyName: ServiceRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                Resource: !Sub 'arn:aws:s3:::${RegionalArtifactsBucketPrefix}-*/*'
              - Sid: SamTranslateDependencyPolicy
                Effect: Allow
                Action:
                  - iam:ListPolicies
                Resource: '*'

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service:
                - codepipeline.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Cache:
        Location: !Sub '${RegionalArtifactsBucketPrefix}-${AWS::Region}/buildcache'
        Type: S3
      Description: !Sub '${Service} production build'
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: ARTIFACTS_BUCKET
            Value: !Sub '${RegionalArtifactsBucketPrefix}-${AWS::Region}'
            Type: PLAINTEXT
        Image: aws/codebuild/python:3.7.1
        Type: LINUX_CONTAINER
      Name: !Ref Service
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        BuildSpec: infrastructure/buildspec.yml
        Type: CODEPIPELINE
      TimeoutInMinutes: 15

  GitHubWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: '{{resolve:secretsmanager:/shared/github-oauth-token}}'
      Filters:
        - JsonPath: '$.ref'
          MatchEquals: 'refs/heads/{Branch}'
      RegisterWithThirdParty: true
      TargetPipeline: !Ref CodePipeline
      TargetAction: GitHub
      TargetPipelineVersion: !GetAtt CodePipeline.Version

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStores:
        - Region: ap-northeast-1
          ArtifactStore:
            Type: S3
            Location: !Sub '${RegionalArtifactsBucketPrefix}-ap-northeast-1'
        - Region: ap-northeast-2
          ArtifactStore:
            Type: S3
            Location: !Sub '${RegionalArtifactsBucketPrefix}-ap-northeast-2'
        - Region: ap-south-1
          ArtifactStore:
            Type: S3
            Location: !Sub '${RegionalArtifactsBucketPrefix}-ap-south-1'
        - Region: ap-southeast-1
          ArtifactStore:
            Type: S3
            Location: !Sub '${RegionalArtifactsBucketPrefix}-ap-southeast-1'
        - Region: ap-southeast-2
          ArtifactStore:
            Type: S3
            Location: !Sub '${RegionalArtifactsBucketPrefix}-ap-southeast-2'
        - Region: ca-central-1
          ArtifactStore:
            Type: S3
            Location: !Sub '${RegionalArtifactsBucketPrefix}-ca-central-1'
        - Region: eu-west-1
          ArtifactStore:
            Type: S3
            Location: !Sub '${RegionalArtifactsBucketPrefix}-eu-west-1'
        - Region: eu-west-2
          ArtifactStore:
            Type: S3
            Location: !Sub '${RegionalArtifactsBucketPrefix}-eu-west-2'
        - Region: eu-west-3
          ArtifactStore:
            Type: S3
            Location: !Sub '${RegionalArtifactsBucketPrefix}-eu-west-3'
        - Region: sa-east-1
          ArtifactStore:
            Type: S3
            Location: !Sub '${RegionalArtifactsBucketPrefix}-sa-east-1'
        - Region: us-east-1
          ArtifactStore:
            Type: S3
            Location: !Sub '${RegionalArtifactsBucketPrefix}-us-east-1'
        - Region: us-east-2
          ArtifactStore:
            Type: S3
            Location: !Sub '${RegionalArtifactsBucketPrefix}-us-east-2'
        - Region: us-west-1
          ArtifactStore:
            Type: S3
            Location: !Sub '${RegionalArtifactsBucketPrefix}-us-west-1'
        - Region: us-west-2
          ArtifactStore:
            Type: S3
            Location: !Sub '${RegionalArtifactsBucketPrefix}-us-west-2'
      RestartExecutionOnUpdate: true
      RoleArn: !GetAtt CodePipelineRole.Arn
      Stages:
        - Name: FetchSource
          Actions:
            - Name: GitHub
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: '1'
              Configuration:
                Repo: !Ref GitHubRepo
                Owner: !Ref GitHubRepoOwner
                Branch: !Ref GitHubRepoBranch
                OAuthToken: '{{resolve:secretsmanager:/shared/github-oauth-token}}'
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: SourceOutput

        - Name: UpdatePipeline
          Actions:
            - Name: UpdatePipeline
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM
                RoleArn: !GetAtt CloudformationRole.Arn
                StackName: !Ref AWS::StackName
                TemplatePath: SourceOutput::infrastructure/pipeline.yml
                ParameterOverrides: !Sub '{"Service": "${Service}", "GitHubRepo": "${GitHubRepo}", "GitHubRepoOwner": "${GitHubRepoOwner}", "GitHubRepoBranch": "${GitHubRepoBranch}", "RegionalArtifactsBucketPrefix": "${RegionalArtifactsBucketPrefix}"}'
              InputArtifacts:
                - Name: SourceOutput

        - Name: Build
          Actions:
            - Name: BuildTestPackage
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref CodeBuildProject
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput

        - Name: Deploy
          Actions:
            - Name: ap-northeast-1
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                RoleArn: !GetAtt CloudformationRole.Arn
                StackName: !Sub '${Service}-functions'
                TemplatePath: BuildOutput::packaged-ap-northeast-1.yml
              InputArtifacts:
                - Name: BuildOutput
              Region: ap-northeast-1

            - Name: ap-northeast-2
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: '1'
              Configuration:
                ActionMode: CREATE_UPDATE
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                RoleArn: !GetAtt CloudformationRole.Arn
                StackName: !Sub '${Service}-functions'
                TemplatePath: BuildOutput::packaged-ap-northeast-2.yml
              InputArtifacts:
                - Name: BuildOutput
              Region: ap-northeast-2
